### ISSUE TITLE
no tag latest

### ISSUE THREAD

**Issue by thorade** [mbonvini/JModelicaDemo#2]
Being a complete docker newbie, I failed to install your docker image, see error message below:
```
make download-image
docker pull modelicainaction/jmodelica
Using default tag: latest
Pulling repository docker.io/modelicainaction/jmodelica
Tag latest not found in repository docker.io/modelicainaction/jmodelica
```

**Comment by thorade** [comment]
Instead, I now tried `make build-image` (after installing Xcode to get `git` and `make`).
Some things I noticed when building the image: 
- I get some warning regarding `apt-utils` not being installed, you might want to install it earlier.
- You are installing some package via `apt-get` and also via `pip`. Is this on purpose? This is for `cython`, `scipy`, `numpy`, `matplotlib` and possibly others.
- If you decide to install `scipy`via pip, you could try using 
  `pip install --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib`,  
  but maybe you have to update pip first using  
  `pip install --upgrade pip setuptools wheel`
  This would also fix the warning about old pip being used.
- `Metis`, `MUMPS` and `libtool`throw some warnings, not sure what that means
- More warnings: autoconf versions not matching
- automake-1.11 is missing
- CMake incompatibilities
- some more warning I don't understand

**Comment by mbonvini** [comment]
Thanks for finding this problem, this commit 3d85cfd1d6dba4e9cc75f7cf2da4d459c32b49a5
should fix the problem associated with the `make download-image` command.

**Comment by thorade** [comment]
Thanks for the quick fix.
Building the image also succeeded and the notebook gives me the same results.
Very nice and very helpful!
